# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI for Alpaca Trading API"
  homepage "https://github.com/alpacahq/cli"
  version "0.0.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.12/cli_0.0.12_darwin_amd64.tar.gz"
      sha256 "e6b286969f0d54ed34e22518dd6bc9c5fb96cbe6096669086f59a813962874ab"

      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.12/cli_0.0.12_darwin_arm64.tar.gz"
      sha256 "a7f43847e3642838a158e56be9f39e4c70d0d7cdd920d5c709c79a07f046578b"

      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.12/cli_0.0.12_linux_amd64.tar.gz"
      sha256 "4b4e7a6bb7626099f995bac437dc1912d752ab329bb4018c81d1c8648460b97d"
      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.12/cli_0.0.12_linux_arm64.tar.gz"
      sha256 "aac702845b2129082adb08c7b8973173bf4e32da4b019bdc6674cc5901e4545b"
      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
  end

  test do
    system bin/"alpaca", "version"
  end
end
