# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI for Alpaca Trading API"
  homepage "https://github.com/alpacahq/cli"
  version "0.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.8/cli_0.0.8_darwin_amd64.tar.gz"
      sha256 "90b786aa8a16e67b9b7f0a26917fef00700f330df89ea10434ed0de223edfb16"

      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.8/cli_0.0.8_darwin_arm64.tar.gz"
      sha256 "63aa4ea8eea00998a8592397140552aa167f3a20433f26c521f61d84414ae5f1"

      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.8/cli_0.0.8_linux_amd64.tar.gz"
      sha256 "836ba7bc71188efc7dbb332ed9cfbd4b1f3dabf5e1cdedae38f5be4cf70b4f56"
      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.8/cli_0.0.8_linux_arm64.tar.gz"
      sha256 "a43eea18cf13138cd065aa54ab6d7cafebcdc320a43ab235db9c0dfd8d463a85"
      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
  end

  test do
    system bin/"alpaca", "version"
  end
end
