# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI for Alpaca Trading API"
  homepage "https://github.com/alpacahq/cli"
  version "0.0.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.9/cli_0.0.9_darwin_amd64.tar.gz"
      sha256 "027a2f031daeaddc7068dcbfaae341f6b1c272f0a9753bcf3e7bbd1f1fd7ed6c"

      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.9/cli_0.0.9_darwin_arm64.tar.gz"
      sha256 "205f1a658759eb30ce2670de6f64d2813100a615ef57c6406939a507d1221555"

      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.9/cli_0.0.9_linux_amd64.tar.gz"
      sha256 "8a6e572cbece42b518f31c7f30477466fcd24e892b5a0efc37a2cf6163fd8642"
      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alpacahq/cli/releases/download/v0.0.9/cli_0.0.9_linux_arm64.tar.gz"
      sha256 "3ee0e4d47e1c84702ed804d73dd4d9ce5c9028744c09c5f1b8698c04311e828f"
      define_method(:install) do
        bin.install "alpaca"
        generate_completions_from_executable(bin/"alpaca", "completion")
      end
    end
  end

  test do
    system bin/"alpaca", "version"
  end
end
